// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: mashupsdk/mashupsdk.proto

package mashupsdk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MashupServerClient is the client API for MashupServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MashupServerClient interface {
	// Indicates to mashup it is time to shutdown.
	Shake(ctx context.Context, in *MashupConnectionConfigs, opts ...grpc.CallOption) (*MashupConnectionConfigs, error)
	OnResize(ctx context.Context, in *MashupDisplayBundle, opts ...grpc.CallOption) (*MashupDisplayHint, error)
	UpsertMashupElements(ctx context.Context, in *MashupDetailedElementBundle, opts ...grpc.CallOption) (*MashupDetailedElementBundle, error)
	UpsertMashupElementsState(ctx context.Context, in *MashupElementStateBundle, opts ...grpc.CallOption) (*MashupElementStateBundle, error)
	Shutdown(ctx context.Context, in *MashupEmpty, opts ...grpc.CallOption) (*MashupEmpty, error)
}

type mashupServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMashupServerClient(cc grpc.ClientConnInterface) MashupServerClient {
	return &mashupServerClient{cc}
}

func (c *mashupServerClient) Shake(ctx context.Context, in *MashupConnectionConfigs, opts ...grpc.CallOption) (*MashupConnectionConfigs, error) {
	out := new(MashupConnectionConfigs)
	err := c.cc.Invoke(ctx, "/mashupsdk.MashupServer/Shake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mashupServerClient) OnResize(ctx context.Context, in *MashupDisplayBundle, opts ...grpc.CallOption) (*MashupDisplayHint, error) {
	out := new(MashupDisplayHint)
	err := c.cc.Invoke(ctx, "/mashupsdk.MashupServer/OnResize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mashupServerClient) UpsertMashupElements(ctx context.Context, in *MashupDetailedElementBundle, opts ...grpc.CallOption) (*MashupDetailedElementBundle, error) {
	out := new(MashupDetailedElementBundle)
	err := c.cc.Invoke(ctx, "/mashupsdk.MashupServer/UpsertMashupElements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mashupServerClient) UpsertMashupElementsState(ctx context.Context, in *MashupElementStateBundle, opts ...grpc.CallOption) (*MashupElementStateBundle, error) {
	out := new(MashupElementStateBundle)
	err := c.cc.Invoke(ctx, "/mashupsdk.MashupServer/UpsertMashupElementsState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mashupServerClient) Shutdown(ctx context.Context, in *MashupEmpty, opts ...grpc.CallOption) (*MashupEmpty, error) {
	out := new(MashupEmpty)
	err := c.cc.Invoke(ctx, "/mashupsdk.MashupServer/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MashupServerServer is the server API for MashupServer service.
// All implementations must embed UnimplementedMashupServerServer
// for forward compatibility
type MashupServerServer interface {
	// Indicates to mashup it is time to shutdown.
	Shake(context.Context, *MashupConnectionConfigs) (*MashupConnectionConfigs, error)
	OnResize(context.Context, *MashupDisplayBundle) (*MashupDisplayHint, error)
	UpsertMashupElements(context.Context, *MashupDetailedElementBundle) (*MashupDetailedElementBundle, error)
	UpsertMashupElementsState(context.Context, *MashupElementStateBundle) (*MashupElementStateBundle, error)
	Shutdown(context.Context, *MashupEmpty) (*MashupEmpty, error)
	mustEmbedUnimplementedMashupServerServer()
}

// UnimplementedMashupServerServer must be embedded to have forward compatible implementations.
type UnimplementedMashupServerServer struct {
}

func (UnimplementedMashupServerServer) Shake(context.Context, *MashupConnectionConfigs) (*MashupConnectionConfigs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shake not implemented")
}
func (UnimplementedMashupServerServer) OnResize(context.Context, *MashupDisplayBundle) (*MashupDisplayHint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnResize not implemented")
}
func (UnimplementedMashupServerServer) UpsertMashupElements(context.Context, *MashupDetailedElementBundle) (*MashupDetailedElementBundle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertMashupElements not implemented")
}
func (UnimplementedMashupServerServer) UpsertMashupElementsState(context.Context, *MashupElementStateBundle) (*MashupElementStateBundle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertMashupElementsState not implemented")
}
func (UnimplementedMashupServerServer) Shutdown(context.Context, *MashupEmpty) (*MashupEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedMashupServerServer) mustEmbedUnimplementedMashupServerServer() {}

// UnsafeMashupServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MashupServerServer will
// result in compilation errors.
type UnsafeMashupServerServer interface {
	mustEmbedUnimplementedMashupServerServer()
}

func RegisterMashupServerServer(s grpc.ServiceRegistrar, srv MashupServerServer) {
	s.RegisterService(&MashupServer_ServiceDesc, srv)
}

func _MashupServer_Shake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MashupConnectionConfigs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MashupServerServer).Shake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashupsdk.MashupServer/Shake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MashupServerServer).Shake(ctx, req.(*MashupConnectionConfigs))
	}
	return interceptor(ctx, in, info, handler)
}

func _MashupServer_OnResize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MashupDisplayBundle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MashupServerServer).OnResize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashupsdk.MashupServer/OnResize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MashupServerServer).OnResize(ctx, req.(*MashupDisplayBundle))
	}
	return interceptor(ctx, in, info, handler)
}

func _MashupServer_UpsertMashupElements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MashupDetailedElementBundle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MashupServerServer).UpsertMashupElements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashupsdk.MashupServer/UpsertMashupElements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MashupServerServer).UpsertMashupElements(ctx, req.(*MashupDetailedElementBundle))
	}
	return interceptor(ctx, in, info, handler)
}

func _MashupServer_UpsertMashupElementsState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MashupElementStateBundle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MashupServerServer).UpsertMashupElementsState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashupsdk.MashupServer/UpsertMashupElementsState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MashupServerServer).UpsertMashupElementsState(ctx, req.(*MashupElementStateBundle))
	}
	return interceptor(ctx, in, info, handler)
}

func _MashupServer_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MashupEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MashupServerServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashupsdk.MashupServer/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MashupServerServer).Shutdown(ctx, req.(*MashupEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

// MashupServer_ServiceDesc is the grpc.ServiceDesc for MashupServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MashupServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mashupsdk.MashupServer",
	HandlerType: (*MashupServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shake",
			Handler:    _MashupServer_Shake_Handler,
		},
		{
			MethodName: "OnResize",
			Handler:    _MashupServer_OnResize_Handler,
		},
		{
			MethodName: "UpsertMashupElements",
			Handler:    _MashupServer_UpsertMashupElements_Handler,
		},
		{
			MethodName: "UpsertMashupElementsState",
			Handler:    _MashupServer_UpsertMashupElementsState_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _MashupServer_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mashupsdk/mashupsdk.proto",
}
